-- ============================================================
-- SQL Schema Setup untuk Hydracker di Supabase
-- Buka Supabase Dashboard -> SQL Editor -> Tempel & Klik 'Run'
-- ============================================================

-- 1. Tabel users
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  berat NUMERIC DEFAULT 0,
  tinggi NUMERIC DEFAULT 0,
  "tanggalLahir" TEXT,
  "targetAir" NUMERIC DEFAULT 2000,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Tambahkan kolom targetAir jika tabel users sudah ada sebelumnya
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "targetAir" NUMERIC DEFAULT 2000;

-- 2. Tabel konsumsi air
CREATE TABLE IF NOT EXISTS public.konsumsi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  jenis TEXT NOT NULL,
  volume NUMERIC NOT NULL,
  tanggal TEXT NOT NULL,
  waktu TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Row Level Security (RLS) Policy
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.konsumsi ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update users" ON public.users FOR UPDATE USING (true);
CREATE POLICY "Allow public delete users" ON public.users FOR DELETE USING (true);

CREATE POLICY "Allow public read konsumsi" ON public.konsumsi FOR SELECT USING (true);
CREATE POLICY "Allow public insert konsumsi" ON public.konsumsi FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update konsumsi" ON public.konsumsi FOR UPDATE USING (true);
CREATE POLICY "Allow public delete konsumsi" ON public.konsumsi FOR DELETE USING (true);

-- 4. Akun default (Admin) untuk demo login
INSERT INTO public.users (nama, username, password, berat, tinggi, "tanggalLahir", "targetAir")
VALUES ('Zaky', 'admin', 'admin123', 60, 170, '2000-01-01', 2000)
ON CONFLICT (username) DO NOTHING;
